### ISSUE TITLE
Text not displaying in refresh cell

### ISSUE THREAD

**Issue by renegade78** [leah/PullToRefresh#1]
Hi,

First of all, can I just say thank you for such awesome code.

I am having a problem though and I'm not sure if I'm doing something really obviously wrong or not!

Basically, the cell displays the arrow and activity indicator fine but no text appears. I was wondering if you knew why this might be? I have installed as per your instructions.

Many thanks in advance!

**Comment by leah** [comment]
Does the demo app work for you okay? Are you customizing the text or label?

**Comment by renegade78** [comment]
Yes, the demo works perfectly! I've left the text and label code as is - I will be customising it later.

I'm wondering if it's to do with the appdelegate as mine is different to yours as I have a tab bar controller.

**Comment by leah** [comment]
Hmm... I changed the demo to a UITabBarController instead of a UINavigationController and it still worked okay. Maybe there's a naming conflict? Do you have another label called "refreshLabel"? Also, does the text show up when you start pulling on the view, or does it never show up at all?

**Comment by renegade78** [comment]
I don't have another label with that name. The text never shows! But the arrow does! Don't worry, I'm obviously doing something wrong!

**Comment by renegade78** [comment]
Thanks for your help, I sorted it. I moved setting the text from the viewdidload method. Thanks though!

**Comment by jonhull** [comment]
I had the same issue. I think it is because I loaded the view via a xib, and the label strings are set in initWithStyle:.  I moved it to viewDidLoad and everything works now...

**Comment by lucaslain** [comment]
YES! Thank you @Jonhull! I had the same problem. Moved the labels to "viewDidLoad" and everything works =). 

ps: @leah ... great work :)

Lucas.
