### ISSUE TITLE
contentInset not cleared properly

### ISSUE THREAD

**Issue by thinkey** [leah/PullToRefresh#2]
thanks for great sharing

if you drag immediately after the last refresh done and before the stop loading animation done, and release the drag with half of the arrow visible(do not trigger a new refresh), the arrow will never gone. This may be fixed by clear the isLoading flag before the animation, or introducing another flag.

increase the animation duration may help on reproducing this.

**Comment by leah** [comment]
Thanks! I've updated the code with your fix.
