### ISSUE TITLE
Despite of updating is finished, 'Loading...' is still running

### ISSUE THREAD

**Issue by hardreggaecafe** [leah/PullToRefresh#29]
Hello

I implemented PulltoRefresh. And when I tested on my TableViewController, indicator shows properly at first.
But despite of updating is finished, 'Loading...' is still running...

What's the matter with my app?

Please let me know how to fix it.

Regards
Noriaki

**Comment by iprebeg** [comment]
Hi Noriaki!

You probably have to call stopLoading: selector after updating either failed or finished

**Comment by hardreggaecafe** [comment]
Absolutely!

I didn't write below line.

```
[self performSelector:@selector(stopLoading) withObject:nil afterDelay:2.0];
```

Thanks for your advice.

**Comment by iprebeg** [comment]
I'm not sure what you actually load but here you are assumimg that loading takes exactly 2 sec, which is probably wrong. 
Better way to do it is calling this selector with no delay on event that signalizes that loading is done or failed, e.g. connection:didFinishLoading or connection:didFailWithError:
